### ISSUE TITLE
Running plot_kernel.py resulted in an error.

### ISSUE THREAD

**Issue by dabaihuaya** [agosztolai/RVGP#2]
In examples\surface_interpolation\
plot_kernel.py, "from RVGP import data" . It seems that there is no "data" module in the "RVGP" package. The error message you received is: "ImportError: cannot import name 'data' from 'RVGP' (c:\users\pc\downloads\compressed\rvgp-main\rvgp-main\RVGP\__init__.py)."

**Comment by agosztolai** [comment]
Hello, 

I am sorry about the delay. I have been travelling for the last few days.

The `data` attribute does not exist. It was part of an earlier, experimental version of the code. Unfortunately, we have overlooked this script when we pushed the final version.

I have fixed it now. Please pull the latest repo.

Let me know if you continue to encounter issues.

Adam
